import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { getMe, getMeQueryOptions } from "@/servers/auth";
import {
  dehydrate,
  HydrationBoundary,
  QueryClient,
} from "@tanstack/react-query";
import { getAuthCookieServer } from "@/lib/auth-cookies";
import { ApiError } from "@/types";
import { AppProvider } from "./providers/query-client-provider";
import { CookiesProvider } from "next-client-cookies/server";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const queryClient = new QueryClient();

  const token = await getAuthCookieServer();
  if (token) {
    try {
      const { data: me } = await getMe();

      if (me) {
        console.log("Fetched current user in layout:", me);
        queryClient.setQueryData(getMeQueryOptions().queryKey, { data: me });
      }
    } catch (err) {
      const error = err as ApiError;
      console.log("Error fetching current user:", err);
      if (error.response?.status == 401) {
        console.log("User not found, clearing auth cookie");
      }
    }
  }

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppProvider>
          <HydrationBoundary state={dehydrate(queryClient)}>
            <CookiesProvider>
              {children}
              <ToastContainer />
            </CookiesProvider>
          </HydrationBoundary>
        </AppProvider>
      </body>
    </html>
  );
}
